name: Publish package to the Maven Central Repository
on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          server-id: central
          server-username: GPG_USERNAME
          server-password: GPG_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE
      - name: Set version
        run: mvn versions:set -DnewVersion=${{ github.event.release.tag_name }}
      - name: Publish package
        run: mvn -P release --batch-mode deploy -DskipTests
        env:
          GPG_USERNAME: ${{ secrets.GPG_USERNAME }}
          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
