name: Deploy Jopus to Maven Central

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          server-id: central
          server-username: GPG_USERNAME
          server-password: GPG_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE
#          server-username: ${{ secrets.GPG_USERNAME }}
#          server-password: ${{ secrets.GPG_PASSWORD }}
#          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
#          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Publish to Maven Central
        run: mvn clean deploy -Pgpg-signing -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }}
        working-directory: jai-connect
        env:
          GPG_USERNAME: ${{ secrets.GPG_USERNAME }}
          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
